"""
diagnose2.py
------------
Prints the first ~20 raw rows of the 4 new datasets so we can identify
the correct header rows and column structures for the cleaner.

Run:
    python diagnose2.py
"""

import pandas as pd
from pathlib import Path

RAW_DIR = Path(r"C:\Users\44782\Desktop\empirical project\data\raw")

# ── GP Appointments (National Overview CSV) ─────────────────────────
print("=" * 70)
print("GP APPOINTMENTS — National_Overview.csv")
print("=" * 70)
path = RAW_DIR / "National_Overview.csv"
if path.exists():
    df = pd.read_csv(path, nrows=10)
    print(f"Shape (first 10 rows read): {df.shape}")
    print(f"Columns: {list(df.columns)}")
    print(df.head(10).to_string())
else:
    print(f"NOT FOUND: {path}")

# ── NHS Workforce (HCHS XLSX) ────────────────────────────────────────
print("\n" + "=" * 70)
print("NHS WORKFORCE — HCHS XLSX")
print("=" * 70)
wf_matches = list(RAW_DIR.glob("*Workforce*"))
if wf_matches:
    wf_path = wf_matches[0]
    print(f"File: {wf_path.name}")
    xl = pd.ExcelFile(wf_path)
    print(f"Sheets: {xl.sheet_names}")
    # Preview first sheet
    df = pd.read_excel(wf_path, sheet_name=xl.sheet_names[0], header=None, nrows=20)
    for i, row in df.iterrows():
        vals = [str(v)[:25] for v in row.values[:6]]
        print(f"  Row {i:>2}: {vals}")
else:
    print("NOT FOUND")

# ── HMT PESA Chapter 4 (XLSX) ────────────────────────────────────────
print("\n" + "=" * 70)
print("HMT PESA — Chapter 4 tables XLSX")
print("=" * 70)
pesa_matches = list(RAW_DIR.glob("PESA*"))
if pesa_matches:
    pesa_path = pesa_matches[0]
    print(f"File: {pesa_path.name}")
    xl = pd.ExcelFile(pesa_path)
    print(f"Sheets: {xl.sheet_names}")
    df = pd.read_excel(pesa_path, sheet_name=xl.sheet_names[0], header=None, nrows=20)
    for i, row in df.iterrows():
        vals = [str(v)[:25] for v in row.values[:6]]
        print(f"  Row {i:>2}: {vals}")
else:
    print("NOT FOUND")

# ── NICE QALY thresholds (already generated, just confirm) ──────────
print("\n" + "=" * 70)
print("NICE QALY THRESHOLDS")
print("=" * 70)
nice_path = RAW_DIR / "nice_qaly_threshold_history.csv"
if nice_path.exists():
    df = pd.read_csv(nice_path)
    print(df.to_string())
else:
    print(f"NOT FOUND: {nice_path} — will be generated by scraper.py")
